### ISSUE TITLE
FID == CODE in new code system

### ISSUE THREAD

**Issue by mwenell** [Webmie/My-Databank-App-and-Extension-2019#29]
PROBLEM

Backend stores only the FID part of the code as fid in the user's profile.

In new system FID = CODE as is. Survey uses code as invite id for the user. we should deliver the data with the code, noit a part of the code.

SOLUTION

If user is using new code, set FID = CODE as is.

**Comment by Njugen** [comment]
FID is now e.g. ANTS-JIOACCIG-LIONBREATH 
The same code entered by the user (which is same code generated by the script, with ALL input parameters in uppercase)
